- .github/workflows/publish_packages_to_npm.yml
- packages/core/CHANGELOG.md
- packages/core/README.md
- packages/core/package.json
- packages/react/CHANGELOG.md
- packages/react/README.md
- packages/react/package.json
- packages/solid/CHANGELOG.md
- packages/solid/README.md
- packages/solid/package.json
- Add readme to npm packages
- Add readme to npm packages
- Updated dependencies
- @pdfslick/core@1.1.3
- Add readme to npm packages
- Updated dependencies
- @pdfslick/core@1.1.3
> Update npm packages and GH workflow

- README.md
- packages/core/CHANGELOG.md
- packages/core/README.md
- packages/core/package.json
- packages/react/CHANGELOG.md
- packages/react/README.md
- packages/react/package.json
- packages/solid/CHANGELOG.md
- packages/solid/README.md
- packages/solid/package.json
* Add credits where credits due
> Add credits

- apps/web/components/Fab.tsx
- apps/web/components/Footer.tsx
- apps/web/components/pdfDocs.ts
- apps/web/pages/examples/horizontal-thumbs.tsx
- apps/web/pages/examples/index.tsx
- apps/web/pages/examples/multiple-documents.tsx
- apps/web/pages/examples/simple-pdf-viewer.tsx
- apps/web/pages/examples/thumbnails-layout.tsx
* Add credits to website
* Update Fab button with example links and goodies
> Add credits website

- apps/web/.eslintrc.js
- apps/web/components/Fab.tsx
- apps/web/components/Footer.tsx
* Updates link attributes 
* Removes Next.js img warning
> Update link attributes and disable Next.js img warning

- apps/web/components/Header.tsx
- apps/web/pages/docs/react-api-reference.md
- apps/web/pages/docs/react-use-pdf-slick-store.md
- apps/web/pages/docs/react-use-pdf-slick.md
- package-lock.json
- package.json
- packages/core/CHANGELOG.md
- packages/core/PDFSlick.ts
- packages/core/lib/pdf_thumbnail_view.ts
- packages/core/lib/pdf_thumbnail_viewer.ts
- packages/core/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/solid/CHANGELOG.md
- packages/solid/package.json
* Updates `pdf.js` and other dependencies versions
* Update docs with details on `usePDFSlick` and `usePDFSlickStore` hooks
* Bump package versions
> Update pdf.js and other dependencies

- .github/workflows/publish_site.yml
- README.md
* Updates workflows
* Adds status badges
> Add status badges

- apps/web/components/docs/Fence.tsx
- apps/web/components/docs/Prism.ts
- apps/web/pages/docs/react-use-pdf-slick-store.md
- apps/web/pages/docs/react-view-documents.md
- apps/web/pages/docs/react.md
- apps/web/pages/docs/solid-api-reference.md
- apps/web/pages/docs/solid.md
- apps/web/pages/docs/svelte.md
* Fixes svelte and shell code highlighting
* Docs broken link correction and content updates
> Docs corrections

- LICENSE
- package-lock.json
- #23 
- Updates deps per dependabot alerts
> Add license file

- apps/svelteweb/src/routes/array-buffer/+page.svelte
- apps/web/examples/ArrayBuffer/PDFNavigation.tsx
- apps/web/examples/ArrayBuffer/index.tsx
- apps/web/pages/examples/array-buffer.tsx
- packages/react/usePDFSlick.tsx
> Array buffer examples

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/solid/CHANGELOG.md
- packages/solid/package.json
> Bump version

- package.json
See https://github.com/pdfslick/pdfslick/issues/32#issuecomment-2116114079
> Add "pdfjs-dist": "3.11.174" in package.json

- .github/workflows/publish_site.yml
> Fix svelte build

- apps/svelteweb/src/routes/custom-viewport/+page.svelte
* Add SvelteKit demo with uploading PDF doc
_TODO_: Need to figure out why pdf.js isn't removing `#hiddenCopyElement` on `_resetView()` https://github.com/mozilla/pdf.js/blob/v3.11.174/web/pdf_viewer.js#L1096
> SvelteKit example with uploading PDF doc

- apps/svelteweb/src/routes/error-handling/+page.svelte
- apps/web/components/Fab.tsx
- apps/web/examples/ErrorHandling.tsx
- apps/web/pages/examples/error-handling.tsx
- assets/pdfs/invalid.pdf
- packages/core/CHANGELOG.md
- packages/core/PDFSlick.ts
- packages/core/package.json
- packages/core/types.ts
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/react/usePDFSlick.tsx
- packages/solid/CHANGELOG.md
- packages/solid/package.json
- packages/solid/usePDFSlick.tsx
* Adds support for error handling in Vanilla JS, Svelte, React and Solid apps #39
> Error handling

- apps/web/pages/docs/svelte.md
> Update svelte css import path in docs

- apps/web/examples/ArrayBuffer/index.tsx
- apps/web/examples/ErrorHandling.tsx
- apps/web/examples/HorizontalThumbs/index.tsx
- apps/web/examples/MultipleDocuments/index.tsx
- apps/web/examples/SimplePDFViewer/index.tsx
- apps/web/examples/ThumbnailsLayout/index.tsx
- apps/web/pages/examples/index.tsx
- apps/web/styles/globals.css
- package-lock.json
- package.json
Fixes issues with layout styles of PDF viewer examples reported in #42 and #52 (based on #53)
> Fix css styles issues with React examples

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/solid/CHANGELOG.md
- packages/solid/package.json
> Bump versions

- apps/web/examples/PDFViewerApp/index.tsx
- packages/core/types.ts
* Add `onProgress` types
* Add `onProgress` example
> Update onProgress tracking

- packages/core/PDFSlick.ts
> Fix TS syntax errors

- apps/web/examples/PDFViewerApp/index.tsx
- package-lock.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/solid/CHANGELOG.md
- packages/solid/package.json
* Add document params example (incl. http range reqs)
* Bump versions
> Release version 2.1.0

- README.md
- apps/svelteweb/src/lib/PDFViewerApp/PDFViewerApp.svelte
- apps/svelteweb/src/routes/array-buffer/+page.svelte
- apps/svelteweb/src/routes/custom-viewport/+page.svelte
- apps/svelteweb/src/routes/dark-mode/+page.svelte
- apps/svelteweb/src/routes/error-handling/+page.svelte
- apps/svelteweb/src/routes/simple-pdf-viewer/+page.svelte
- apps/vanillajs/index.html
- apps/web/pages/docs/svelte.md
* Fix svelte and vanilla JS demos
> Fix svelte and vanilla JS demos

- apps/solidweb/package.json
- apps/svelteweb/package.json
- apps/vanillajs/package.json
- apps/web/package.json
- config/eslint-config-custom/package.json
- config/rollup-config/package.json
- config/tsconfig/package.json
- package-lock.json
- packages/core/package.json
- packages/react/package.json
- packages/solid/package.json
* Fix workflow
* Add missing reatc/zustand dependency
> Fix workflow, add missing deps

- apps/svelteweb/src/app.css
- apps/svelteweb/src/lib/PDFViewerApp/Toolbar/ZoomSelector.svelte
- apps/svelteweb/src/lib/Tooltip.svelte
- apps/svelteweb/src/lib/components/ui/dropdown-menu/dropdown-menu-checkbox-item.svelte
- apps/svelteweb/src/lib/components/ui/dropdown-menu/dropdown-menu-content.svelte
- apps/svelteweb/src/lib/components/ui/dropdown-menu/dropdown-menu-group-heading.svelte
- apps/svelteweb/src/lib/components/ui/dropdown-menu/dropdown-menu-item.svelte
- apps/svelteweb/src/lib/components/ui/dropdown-menu/dropdown-menu-label.svelte
- apps/svelteweb/src/lib/components/ui/dropdown-menu/dropdown-menu-radio-item.svelte
- apps/svelteweb/src/lib/components/ui/dropdown-menu/dropdown-menu-separator.svelte
- apps/svelteweb/src/lib/components/ui/dropdown-menu/dropdown-menu-shortcut.svelte
- apps/svelteweb/src/lib/components/ui/dropdown-menu/dropdown-menu-sub-content.svelte
- apps/svelteweb/src/lib/components/ui/dropdown-menu/dropdown-menu-sub-trigger.svelte
- apps/svelteweb/src/lib/components/ui/dropdown-menu/index.ts
- apps/svelteweb/src/lib/utils.ts
- apps/svelteweb/src/routes/array-buffer/+page.svelte
- apps/svelteweb/src/routes/custom-viewport/+page.svelte
- apps/svelteweb/src/routes/dark-mode/+page.svelte
- apps/svelteweb/src/routes/simple-pdf-viewer/+page.svelte
- apps/svelteweb/tailwind.config.js
- package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/solid/CHANGELOG.md
- packages/solid/package.json
* Generate [provenance statements](https://docs.npmjs.com/generating-provenance-statements#example-github-actions-workflow)
> Generate npm provenance statements

- .github/workflows/publish_packages_to_npm.yml
- .github/workflows/publish_site.yml
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/solid/CHANGELOG.md
- packages/solid/package.json
* Add pvovenance config on each published package
> Generate npm provenance statements on each package

- .github/workflows/publish_packages_to_npm.yml
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/solid/CHANGELOG.md
- packages/solid/package.json
* Fix publishibg issue with npm provenance
> Fix generate npm provenance statements on each package

- apps/web/examples/PDFViewerApp/Toolbar/SearchBar.tsx
- apps/web/examples/PDFViewerApp/Toolbar/index.tsx
- packages/core/PDFSlick.ts
* Adds FindController in PDFSlick
* Add SearchBar in demo app
> Add find controller, add search in demo

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/solid/CHANGELOG.md
- packages/solid/package.json
> Bump packages versions

- README.md
- apps/web/components/Footer.tsx
- apps/web/styles/globals.css
- packages/core/README.md
- packages/react/README.md
- packages/solid/README.md
* Fix CSS dark mode issues with the examples
* Update docs
> Fixes and updates
